services:
  cuda-dev:
    build: .
    container_name: example-cuda
    command: ./main
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]